Vagrant.configure(2) do |config|
  config.vm.hostname = "voltron"
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.linked_clone = true
  end

  config.vm.network "forwarded_port", guest: 5555, host: 5556

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get upgrade -y
    sudo apt-get install -y \
        build-essential \
        gdb \
        zsh \
        python3-pip
    sudo pip3 install -e /vagrant/repo
    echo "source /vagrant/repo/dbgentry.py" >/home/vagrant/.gdbinit
    echo "voltron init" >>/home/vagrant/.gdbinit
    echo "set disassembly-flavor intel" >>/home/vagrant/.gdbinit
    echo '{"server":{"listen":{"tcp":["0.0.0.0",5555]}}}' >/home/vagrant/.voltron/config
  SHELL
end
