Vagrant.configure(2) do |config|
  config.vm.hostname = "voltron"
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.linked_clone = true
  end

  config.vm.network "forwarded_port", guest: 5555, host: 5556

  config.vm.synced_folder "../", "/voltron"
  config.vm.synced_folder "~/shared", "/shared"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade -y
    apt-get install -y \
        build-essential \
        gdb \
        zsh \
        python3-pip \
        lldb-3.8
    pip3 install six --upgrade
    su - vagrant -c "cd /voltron ; ./install.sh"
    mkdir -p /home/vagrant/.voltron
    chown vagrant:vagrant /home/vagrant/.voltron -R
    cat >/home/vagrant/.voltron/config <<END
general:
  debug_logging: true
END
  SHELL
end
